image: python:3.9

cache:
  paths:
    - .cache/pip

stages:
  - build
  - test

before_script:
  - pip install --upgrade pip
  - pip install robotframework
  - pip install robotframework-browser
  - rfbrowser init

build:
  stage: build
  script:
    - robot RobotFrameworkSetup.robot 

test:
  stage: test
  script:
    - robot RobotFrameworkSetup.robot 
  artifacts:
    paths:
      - output.xml
      - report.html
      - log.html
